name: ci
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        with:
          gh_token: ${{secrets.GH_TOKEN}}
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ gh_token }}
